<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.GoogleServices.AdsBase</PackageId>
		<PackageVersion>23.2.0</PackageVersion>
		<AssemblyVersion>23.2.0</AssemblyVersion>
		<FileVersion>23.2.0</FileVersion>
		<Version>23.2.0</Version>
		<Title>Anjo Android GoogleServices Ads Base SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.GoogleServices</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) bindings for Google Play Services library 'com.google.android.gms:play-services-ads-base'.</Description>
		<PackageReleaseNotes>GoogleServices Ads Base SDK v23.2.0</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, NET MAUI, Google Play Services, Admob, Banner, Interstitial, Rewarded Interstitial</PackageTags>
		<Summary>The Google Mobile Ads SDK is the latest generation in Google mobile advertising, featuring refined ad formats and streamlined APIs for access to mobile ad networks and advertising solutions. The SDK enables mobile app developers to maximize their monetization in native mobile apps.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\play-services-ads-base-23.2.0.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.GooglePlayServices.Basement" Version="118.2.0.5" />
	</ItemGroup>
</Project>