<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.GoogleServices.Ads</PackageId>
		<PackageVersion>22.6.0</PackageVersion>
		<AssemblyVersion>22.6.0</AssemblyVersion>
		<FileVersion>22.6.0</FileVersion>
		<Version>22.6.0</Version>
		<Title>Anjo Android GoogleServices Ads SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.GoogleServices</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) bindings for Google Play Services library 'com.google.android.gms:play-services-ads'.</Description>
		<PackageReleaseNotes>GoogleServices Ads SDK v22.6.0</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Google Play Services, Admob, Banner, Interstitial, Rewarded Interstitial</PackageTags>
		<Summary>The Google Mobile Ads SDK is the latest generation in Google mobile advertising, featuring refined ad formats and streamlined APIs for access to mobile ad networks and advertising solutions. The SDK enables mobile app developers to maximize their monetization in native mobile apps.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\play-services-ads-22.6.0.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Xamarin.AndroidX.Browser" Version="1.7.0.1" />
		<PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.2" />
		<PackageReference Include="Xamarin.AndroidX.Core" Version="1.12.0.3" />
		<PackageReference Include="Xamarin.GooglePlayServices.Ads.Identifier" Version="118.0.1.8" />
		<PackageReference Include="Xamarin.GooglePlayServices.AppSet" Version="16.0.2.8" />
		<PackageReference Include="Xamarin.GooglePlayServices.Basement" Version="118.2.0.5" />
		<PackageReference Include="Xamarin.GooglePlayServices.Tasks" Version="118.0.2.6" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Anjo.Android.GoogleServices.AdsBase\Anjo.Android.GoogleServices.AdsBase.csproj" />
		<ProjectReference Include="..\Anjo.Android.GoogleServices.AdsLite\Anjo.Android.GoogleServices.AdsLite.csproj" />
	</ItemGroup>
</Project>